### ISSUE TITLE
Printing STACK elements

### ISSUE THREAD

**Issue by ssi-anik** [Algorithm-archive/Learn-Data_Structure-Algorithm-by-PHP#1]
Can we print stack elements?
https://github.com/Algorithm-archive/Learn-Data_Structure-Algorithm-by-PHP/blob/master/Data%20Structure/Stack/Stack.php#L28

**Comment by me-shaon** [comment]
This mostly depends on implementation. Though as definition **Stack** will only be accessed via public methods like `push()`, `pop()`, `top()` etc. Which means it won't be possible to access any random element from the stack. But if you want to show all the elements of the stack (Whether for testing purpose or else), I think you can expose a method like `printElements()`. Otherwise, the only choice left is to recursively pop all the elements and also push them in a new stack, just to see the entire list. It won't harm to expose a method like `printElements()` as it just a read-only operation.

**Comment by me-shaon** [comment]
@ssi-anik, It actually makes sense not to expose a method like **printAll()** from **Stack** class. Fixed it. Thanks, man!
